### ISSUE TITLE
Don't hide admin settings when limiting app to certain groups

### ISSUE THREAD

**Issue by q-wertz** [nextcloud/integration_mattermost#13]
Currently also the admin settings are hidden as soon as the app is limited to groups where the admin user is not part of.

Hiding the personal configs makes sense but I think the admin settings should still be visible. Or is this an upstream issue?

**Comment by kyteinsky** [comment]
Hi, I think it is intended as this way and is related to the server repository. I have attached a patch in case you want to have the feature. Also, here is the commit in a branch in the server repo with the change: https://github.com/nextcloud/server/compare/master...fix/always-enable-apps-admin. I don't hope for it to be merged though.  
[always-enable-app-for-admin.txt](https://github.com/nextcloud/integration_mattermost/files/12596457/always-enable-app-for-admin.txt)

**Comment by q-wertz** [comment]
Thanks for the information. I understand that not every app should be enabled for all admins. 
But for me enabling an app for a user (resp. admin in that case) and enabling the possibility to configure an app from the administrator point of view are two different things. 

From your message I conclude NC does not differ between those two, right?

**Comment by kyteinsky** [comment]
@q-wertz Yes, it does not differentiate between the two, for now at least.
