### ISSUE TITLE
How to use webhook?

### ISSUE THREAD

**Issue by yewkay** [nextcloud/integration_mattermost#14]
I saw there is a "Enable webhook " option and relates to calendar inside options? 
May I know if there's any documentation for it? I'm extremely interested in linking the calendar function in NC to mattermost. eg: create events, see daily events, see event details, etc.

**Comment by julien-nc** [comment]
Hey. This feature is meant to be automatically configured by a Mattermost bot (still in development as far as I know).

If things don't move on the Mattermost bot side, we will maybe extend the feature on the Nextcloud side to send messages to a specific channel using the integration authentication. To be continued.

**Comment by yewkay** [comment]
is there a plugin for mattermost side to install?

**Comment by julien-nc** [comment]
Not yet. You can consider this feature useless for now in this app.

**Comment by SimJoSt** [comment]
@julien-nc is there a public place to follow the development of the Mattermost bot/app/integration?
I would love to share suggestions like expanding link previews when sharing internal links, etc.
