### ISSUE TITLE
Send to Mattermost --> Failed to load Mattermost channels

### ISSUE THREAD

**Issue by BKapelari** [nextcloud/integration_mattermost#17]
Hello,

I have connected our Mattermost instance in the admin settings and in the personal settings as well. No Errors there.
But the Dashboard-Widget does not work and asks for connecting. Error in the browser console:
```
https:mynextcloudurl.com/index.php/apps/integration_mattermost/notifications
[HTTP/2 400 Bad Request 1473ms]
```

And if I try to send a file to Mattermost I got a Nextcloud notification "Failed to load Mattermost channels". In the browser console, Ican find this API response:

`{"id":"api.context.404.app_error","message":"Sorry, we could not find the page.","detailed_error":"There doesn't appear to be an api call for the url='/mattermost/api/v4/users/uifoiywecjym5mfcqtdhk8rfgo/channels'.  Typo? are you missing a team_id or user_id as part of the url?","status_code":404}`

**Comment by julien-nc** [comment]
Hi,

Which Mattermost version are you using? If it's too old, I assume the API endpoint to get channels or notifications may have changed.

I think I only used Mattermost instances that were > 7.0.

If this is the cause for this 404, we should properly document which Mattermost versions this integration app is compatible with.

**Comment by KanenasPL** [comment]
Same here – Mattermost 7.2.0

**Comment by kyteinsky** [comment]
Hello @KanenasPL @BKapelari  
Please post the version of the Nextcloud server, the Mattermost integration and the Mattermost instance that you're using.  
It seems you're using an older version of the Mattermost instance that does not support API v4. Please use version >= 5.0

**Comment by BKapelari** [comment]
I could fix the problem already. The Mattermost Version was to old.

**Comment by kyteinsky** [comment]
@KanenasPL If your issue is still not resolved, consider opening another issue since the original one has been resolved.
