### ISSUE TITLE
Enable navigation link by default for all users

### ISSUE THREAD

**Issue by absort0** [nextcloud/integration_mattermost#20]
Hi Julien, thanks for all the work done in this app, it is really handy.

I'm wondering if there is already a way - or a feature underway? -  that would allow admins to enable by default the **navigation link** for all users. For my use purposes, this could be done either in the admin web interface, with an `occ` command or by having a configuration file. This would be very handy as we want all users to have fast access to our Mattermost instance. 

Thanks!

**Comment by kyteinsky** [comment]
I don't know if this caters to a much wider audience, but it couldn't hurt much to include it. Please consider making a pull request. I am also marking it as a good-first-issue in case any new contributor is interested.
